apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-hub
  namespace: kafka-hub
  annotations:
    strimzi.io/kraft: enabled
    strimzi.io/node-pools: enabled
spec:
  kafka:
    version: 3.7.0
    metadataVersion: 3.7-IV4
    replicas: 1
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        memory: 1Gi

    config:
      auto.create.topics.enable: false
      log.cleanup.policy: "delete" # Cannot use 'compact' due to empty key in our data format
      log.retention.bytes: 6442450944 # no default upper size limit, set to 6Gi
      max.message.bytes: 1048576 # if you change this you need to review the kafka docs

      transaction.state.log.min.isr: 1
      min.insync.replicas: 1
      default.replication.factor: 1
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      num.partitions: 1

  zookeeper:
    replicas: 1
    storage:
      size: 20Gi
      type: persistent-claim
      deleteClaim: false
