---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: db-postgres
  namespace: flux-system
spec:
  dependsOn:
    - name: cloudnative-pg-operator
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./database/postgres/local
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: db-postgres-migration
  namespace: flux-system
spec:
  dependsOn:
    - name: db-postgres
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./database/postgres-migration/local
  prune: true
  wait: true
