---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: eliot-erp-sales-sync-worker
  namespace: flux-system
spec:
  dependsOn:
    - name: db-postgres
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./application/eliot/services/worker/electrum-asset-platform/local/
  prune: true
  wait: true
