---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: eliot-erp-sales-sync-worker
  namespace: eliot
spec:
  interval: 15m
  chart:
    spec:
      chart: k8s-service
      version: v0.2.24
      sourceRef:
        kind: HelmRepository
        name: gruntwork-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    deploymentAnnotations:
      reloader.stakater.com/search: "true"
    containerImage:
      repository: jeffail/benthos
      tag: 4.24
      pullPolicy: IfNotPresent

    fullnameOverride: "eliot-erp-sales-sync-worker"
    applicationName: "eliot-erp-sales-sync-worker"
    replicaCount: 1
    namespace: "eliot"

    containerArgs:
      - "-c"
      - "/etc/benthos/erp-sales-sync.yaml"

    configMaps:
      eliot-erp-sales-sync-worker-cm:
        as: volume
        mountPath: /etc/benthos

    deploymentStrategy:
      enabled: true
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1

    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /ping
        port: 4195
      periodSeconds: 10
      timeoutSeconds: 2
      initialDelaySeconds: 20

    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /ready
        port: 4195
      periodSeconds: 10
      timeoutSeconds: 2
      initialDelaySeconds: 20

    containerPorts:
      debug:
        port: 4195
        protocol: TCP

    service:
      enabled: true
      ports:
        debug:
          port: 4195
          targetPort: debug
          protocol: TCP

    serviceMonitor:
      enabled: true
      namespace: eliot
      labels: { }
      endpoints:
        default:
          interval: 10s
          scrapeTimeout: 10s
          honorLabels: true
          path: /metrics
          port: debug
          scheme: http

    affinity: {}

    tolerations: []

    nodeSelector: {}

    secrets:
      pg-core-super-secret:
        as: environment
        items:
          postgres.db.name:
            envVarName: DB_NAME
          postgres.host:
            envVarName: DB_HOST
          postgres.password:
            envVarName: DB_PASSWORD
          postgres.user:
            envVarName: DB_USER
          postgres.port:
            envVarName: DB_PORT
