---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: strimzi-kafka-operator
  namespace: kafka-controller
spec:
  interval: 30m
  chart:
    spec:
      chart: strimzi-kafka-operator
      version: 0.40.0
      sourceRef:
        kind: HelmRepository
        name: strimzi-charts
        namespace: flux-system
      interval: 15m
  maxHistory: 2
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    watchAnyNamespace: true
    replicas: 1
    featureGates: "+UseKRaft,+KafkaNodePools,+UnidirectionalTopicOperator"
    resources:
      limits:
        memory: 384Mi
        cpu: 1000m
      requests:
        memory: 384Mi
        cpu: 200m

    dashboards:
      enabled: false
      namespace: monitoring
      label: grafana_dashboard
      labelValue: "1"
      annotations:
        grafana_folder: "kafka"