apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: debezium-pg-core-connector
  labels:
    strimzi.io/cluster: debezium-kafkaconnect
  namespace: kafka-hub
spec:
  config:
    #table config
    table.include.list: public.debezium_heartbeat,public.stock_picking
    #message key transformer
    # message.key.columns: postgres.orders:customer_id
