---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-core
  namespace: database
spec:
  instances: 1

  resources:
    requests:
      cpu: 200m
      memory: 1Gi
    limits:
      memory: 1Gi

  storage:
    size: 30Gi
